# Generated by Django 2.2.5 on 2020-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scrape',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('adress', models.TextField(blank=True)),
                ('coordinate', models.TextField(blank=True)),
                ('homepage', models.TextField(blank=True)),
                ('hours', models.TextField(blank=True)),
            ],
        ),
    ]
