# Generated by Django 2.2.5 on 2020-02-05 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap_scrape', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrape',
            name='adress',
        ),
        migrations.RemoveField(
            model_name='scrape',
            name='coordinate',
        ),
        migrations.RemoveField(
            model_name='scrape',
            name='homepage',
        ),
        migrations.RemoveField(
            model_name='scrape',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='scrape',
            name='title',
        ),
        migrations.AddField(
            model_name='scrape',
            name='dollar',
            field=models.FloatField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
