# Generated by Django 2.2.5 on 2020-02-05 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap_scrape', '0002_auto_20200205_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='dollar',
            field=models.CharField(max_length=100),
        ),
    ]
