# Generated by Django 2.2.5 on 2020-02-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gmap_scrape', '0003_auto_20200205_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrape',
            name='dollar',
            field=models.FloatField(),
        ),
    ]
